version: '3.8'

services:
  api:
    image: iamsoumyamishra7/superconductor-mlops:latest
    container_name: fastapi_app
    ports:
      - "8000:8000"
    restart: always

  streamlit:
    image: iamsoumyamishra7/superconductor-mlops:latest
    container_name: streamlit_app
    ports:
      - "8501:8501"
    command: streamlit run frontend/app.py --server.port=8501 --server.address=0.0.0.0
    restart: always